deploy:
  fitnesse: false

data:
  dataDividers: "cora jsClient alvin alvinTestSystem"

externalAccess:
  systemUrl: https://cora.alvin-portal.org
  systemRestUrl: https://cora.alvin-portal.org/rest/
  deploymentName: Alvin - Cora
  loginRestUrl: https://cora.alvin-portal.org/login/rest/
  restToPathSystem: /rest/
  iiifToPathSystem: /iiif/
  loginPathSystem: /login/rest/
  alvinClientPath: alvinclient

apache:
  useExtraEnvs: true
  extraEnvs: 
    - name: ALVIN_CLIENT_CONTEXT_ROOT_ARG
      value: alvinclient

django:
  allowedHosts: "*"
  
shibboleth:
  domain: pre

port:
  apache: 30981

fitnesse:
  contextRoot: fitnesse
  baseUrl: https://cora.alvin-portal.org/
  loginUrl: https://cora.alvin-portal.org/login/