deploy:
  fitnesse: true

data:
  dataDividers: "cora jsClient alvin alvinPreview alvinTestSystem alvinProduction alvinData"
  exampleUsers: 
    - "141414"
    - "151515"
    - "coraUser:4412566252284358"
  
externalAccess:
  systemUrl: https://preview.alvin.cora.epc.ub.uu.se
  systemRestUrl: https://preview.alvin.cora.epc.ub.uu.se/rest/
  deploymentName: Alvin - preview ðŸ‘€
  loginRestUrl: https://preview.alvin.cora.epc.ub.uu.se/login/rest/
  loginPathSystem: /login/rest/
  alvinClientPath: alvinclient

apache:
  useExtraEnvs: true
  extraEnvs: 
    - name: ALVIN_CLIENT_CONTEXT_ROOT_ARG
      value: alvinclient

django:
  allowedHosts: "*"
  
shibboleth:
  domain: previewepc

port:
  apache: 30981

fitnesse:
  contextRoot: fitnesse
  baseUrl: https://preview.alvin.cora.epc.ub.uu.se/
  loginUrl: https://preview.alvin.cora.epc.ub.uu.se/login/