apiVersion: v1
kind: Secret
metadata:
  name: alvin-secret
type: Opaque
data:
  POSTGRES_USER: YWx2aW4=
  POSTGRES_PASSWORD: YWx2aW4=
  binaryConverterLoginId: c3lzdGVtb25lQWRtaW5Ac3lzdGVtLmNvcmEudXUuc2U=
  binaryConverterAppToken: NWQzZjNlZDQtNDkzMS00OTI0LTlmYWEtOGVhZjVhYzY0NTdl


#echo -n 'Hello, World!' | base64
