deploy:
  fitnesse: true
  jsclient: false
  divaclient: true
  playwright: true

data:
  dataDividers: "cora jsClient diva divaPreview divaPre divaProduction divaClient"

externalAccess:
  systemUrl:  http://172.18.0.15:31982
  loginRestUrl: http://172.18.0.15:31982/login/rest/
shibboleth:
  domain: build
port:
  apache: 31982

security:
  divaClientSecureSessionCookie: false
  divaClientAppTokenUsers: [{"displayName":"Diva Admin","loginId":"divaAdmin@cora.epc.ub.uu.se","appToken":"49ce00fb-68b5-4089-a5f7-1c225d3cf156"}]
