deploy:
  fitnesse: true
  divaclient: true
  playwright: false

data:
  dataDividers: "cora jsClient diva divaPre divaClient"

security:
  divaClientAppTokenUsers: []

externalAccess:
  systemUrl: https://pre.diva-portal.org
  restToPathSystem: /rest/
  iiifToPathSystem: /iiif/
  loginPathSystem: /login/rest/
  divaClientBasePath: /divaclient
  
apache:
  useExtraEnvs: true
  extraEnvs: 
    - name: DIVA_CLIENT_CONTEXT_ROOT_ARG
      value: divaclient

shibboleth:
  domain: pre

port:
  apache: 30982

fitnesse:
  contextRoot: fitnesse
  baseUrl: https://pre.diva-portal.org/
  loginUrl: https://pre.diva-portal.org/login/
