deploy:
  fitnesse: true
  divaclient: true
  playwright: true

data:
  dataDividers: "cora jsClient diva divaPreview divaPre divaProduction divaClient"

security:
  divaClientAppTokenUsers: [{"displayName":"Diva Admin","loginId":"divaAdmin@cora.epc.ub.uu.se","appToken":"49ce00fb-68b5-4089-a5f7-1c225d3cf156"}]

externalAccess:
  systemUrl: https://preview.diva.cora.epc.ub.uu.se
  deploymentName: DiVA - preview ðŸ‘€
  loginRestUrl: https://preview.diva.cora.epc.ub.uu.se/login/rest/
  loginPathSystem: /login/rest/
  divaClientBasePath: /divaclient
  
apache:
  useExtraEnvs: true
  extraEnvs: 
    - name: DIVA_CLIENT_CONTEXT_ROOT_ARG
      value: divaclient

shibboleth:
  domain: previewepc

port:
  apache: 30982

fitnesse:
  contextRoot: fitnesse
  baseUrl: https://preview.diva.cora.epc.ub.uu.se/
  loginUrl: https://preview.diva.cora.epc.ub.uu.se/login/
