deploy:
  fitnesse: false
  divaclient: true
  playwright: false

data:
  dataDividers: "cora jsClient diva divaPre divaClient"
  exampleUsers:

externalAccess:
  systemUrl: https://pre.diva-portal.org
  systemRestUrl: https://pre.diva-portal.org/rest/
  deploymentName: DiVA - PRE
  loginRestUrl: https://pre.diva-portal.org/login/rest/
  loginPathSystem: /login/rest/
  divaClientBasePath: /divaclient

apache:
  useExtraEnvs: true
  extraEnvs:
    - name: DIVA_CLIENT_CONTEXT_ROOT_ARG
      value: divaclient

port:
  apache: 30982
