deploy:
  fitnesse: true
  jsclient: false
  divaclient: true
  playwright: true

data:
  dataDividers: "cora jsClient diva divaPreview divaPre divaProduction divaClient"
  exampleUsers: 
    - "141414"
    - "161616"
    - "coraUser:491144693381458"
    - "user:182924359788077"
    - "user:8985188367779791"
    - "coraUser:491201365536105"
    - "playwrightTester"

externalAccess:
  systemUrl:  http://172.18.0.15:31982
  systemRestUrl:  http://172.18.0.15:31982/rest/
  loginRestUrl: http://172.18.0.15:31982/login/rest/
shibboleth:
  domain: build
port:
  apache: 31982

security:
  divaClientSecureSessionCookie: false
  divaClientAppTokenUsers: [{"displayName":"Diva Admin","loginId":"divaAdmin@cora.epc.ub.uu.se","appToken":"49ce00fb-68b5-4089-a5f7-1c225d3cf156"}]
