deploy:
  fitnesse: true
  jsclient: false

data:
  dataDividers: "cora jsClient systemOne testSystem"

externalAccess:
  systemUrl:  http://172.18.0.15:31980
  loginRestUrl: http://172.18.0.15:31980/login/rest/

port:
  apache: 31980
