deploy:
  fitnesse: true

data:
  dataDividers: "cora jsClient systemOne testSystem"
  exampleUsers: 
    - "141414"
  
externalAccess:
  systemUrl: https://preview.systemone.cora.epc.ub.uu.se
  systemRestUrl: https://preview.systemone.cora.epc.ub.uu.se/rest/
  deploymentName: SystemOne - preview ðŸ‘€
  loginRestUrl: https://preview.systemone.cora.epc.ub.uu.se/login/rest/
  loginPathSystem: /login/rest/

port:
  apache: 30980

fitnesse:
  contextRoot: fitnesse
  baseUrl: https://preview.systemone.cora.epc.ub.uu.se/
  loginUrl: https://preview.systemone.cora.epc.ub.uu.se/login/